#!/usr/bin/env bash
# check-team-exists.sh — inspect ~/.claude/teams/harness-team/config.json and
# emit one of three states on stdout:
#
#   absent   — no team file. The lead must call TeamCreate before any Agent({}).
#   present  — team file exists with a valid (non-corrupt) member list. The lead
#              must NOT call TeamCreate. Per-lane spawn decisions are then made
#              by spawn-lane-decision.sh.
#   corrupt  — team file exists but contains suffixed names like analyst-1-2
#              (Claude Code's auto-disambiguation when an Agent({name:...}) call
#              collided with a live teammate). The team is no longer trustworthy.
#              The lead must surface the remediation message and stop.
#
# Per-lane membership is NOT checked here — that lives in spawn-lane-decision.sh.
# This script only answers "should the lead call TeamCreate or not, and is the
# existing team safe to reuse?".
#
# Exit code is always 0; the caller branches on stdout.

set -u

TEAM_CFG="$HOME/.claude/teams/harness-team/config.json"

__resolve_project_root() {
  local d="${1:-$PWD}"
  while [ "$d" != "/" ]; do
    [ -d "$d/.bare" ] && { echo "$d"; return 0; }
    d="$(dirname "$d")"
  done
  echo "${1:-$PWD}"
}

ROOT="$(__resolve_project_root "${1:-$PWD}")"

# >>> TEST-LOG (REMOVE AFTER DEBUGGING) — investigates why /harness-team-lead crashes
__test_log() {
  local logdir="$ROOT/.my-harness/logs"
  mkdir -p "$logdir" 2>/dev/null
  printf '[%s] [pid=%d] [check-team-exists] %s\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$$" "$*" \
    >> "$logdir/harness-test.log" 2>/dev/null
}
__test_log "STARTED team_cfg=$TEAM_CFG cfg_exists=$([ -f "$TEAM_CFG" ] && echo yes || echo no) cfg_size=$(stat -f %z "$TEAM_CFG" 2>/dev/null || stat -c %s "$TEAM_CFG" 2>/dev/null || echo 0)"
# <<< TEST-LOG

if [ ! -f "$TEAM_CFG" ]; then
  # >>> TEST-LOG
  __test_log "RESULT state=absent"
  # <<< TEST-LOG
  echo "absent"
  exit 0
fi

if command -v jq >/dev/null 2>&1; then
  MEMBERS=$(jq -r '.members[].name // empty' "$TEAM_CFG" 2>/dev/null)
else
  MEMBERS=$(grep -o '"name"[[:space:]]*:[[:space:]]*"[^"]*"' "$TEAM_CFG" 2>/dev/null \
    | sed 's/.*"\([^"]*\)"$/\1/' \
    | grep -v '^harness-team$')
fi

CORRUPT=$(printf '%s\n' "$MEMBERS" \
  | grep -E '^(analyst|engineer|e2e-reviewer|reviewer)-[0-9]+-[0-9]+$' \
  | tr '\n' ' ' | sed 's/ $//')

# >>> TEST-LOG (REMOVE AFTER DEBUGGING)
MEMBERS_LIST=$(printf '%s' "$MEMBERS" | tr '\n' ',' | sed 's/,$//')
__test_log "MEMBERS_DETECTED count=$(printf '%s\n' "$MEMBERS" | grep -c . 2>/dev/null || echo 0) names=[$MEMBERS_LIST] corrupt_names=[$CORRUPT]"
# <<< TEST-LOG

if [ -n "$CORRUPT" ]; then
  # >>> TEST-LOG
  __test_log "RESULT state=corrupt names=[$CORRUPT]"
  # <<< TEST-LOG
  echo "corrupt"
  cat >&2 <<EOF
::error:: harness-team has suffixed names: $CORRUPT
         These are auto-generated by Claude Code when Agent({name:...}) is
         called with a name that already belongs to a live teammate. Once
         present, the team configuration is no longer trustworthy.
         Remediation: rm -rf ~/.claude/teams/harness-team/ and start a fresh
         Claude Code session, then re-run /harness-team-lead.
EOF
  exit 0
fi

# >>> TEST-LOG (REMOVE AFTER DEBUGGING)
__test_log "RESULT state=present"
# <<< TEST-LOG
echo "present"
exit 0
