-- Initial migration including production-grade tables.
-- Generated by hand to bootstrap the harness; subsequent changes go through
-- `pnpm db:generate --name <descriptive>`. NEVER run `drizzle-kit push`.

CREATE TABLE IF NOT EXISTS users (
  id              TEXT PRIMARY KEY NOT NULL,
  email           TEXT NOT NULL UNIQUE,
  display_name    TEXT NOT NULL,
  password_hash   TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  token_hash_hex  TEXT PRIMARY KEY NOT NULL,
  user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  issued_at       TEXT NOT NULL,
  expires_at      TEXT NOT NULL,
  consumed_at     TEXT
);

-- audit_log: append-only. The harness deploy step grants only INSERT to the
-- application role; UPDATE / DELETE are restricted to a separate admin role.
CREATE TABLE IF NOT EXISTS audit_log (
  id            TEXT PRIMARY KEY NOT NULL,
  actor_id      TEXT NOT NULL,
  action        TEXT NOT NULL,
  resource      TEXT NOT NULL,
  metadata      TEXT,
  ip            TEXT,
  occurred_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor  ON audit_log (actor_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log (action,   occurred_at);
