{ config, pkgs, lib, ... }:

# claude-code / codex / cli-proxy-api / hermes-agent / openclaw are all
# provided by numtide/llm-agents.nix via the overlay wired in flake.nix
# (pkgs.llm-agents.<name>). No more self-built buildNpmPackage / buildFHSEnv
# derivations under ./pkgs (deleted in 7.33.0) — every agent is a binary-cache
# hit from https://cache.numtide.com, daily auto-updated upstream, with
# meta.mainProgram set so service modules can use lib.getExe.
{
  # harness options — set via harness-overlay.nix (auto-generated by setup-oci-vm-nixos.sh).
  # harness.hermesAgentEnabled = true  → activates services/hermes-agent.nix
  # harness.openClawEnabled = true     → activates services/openclaw.nix (7.30.0)
  # harness.tailscaleEnabled = true    → activates services/tailscale.nix (7.32.0)
  # Exactly one of hermesAgentEnabled / openClawEnabled may be true (Q12.5 single-select).
  options.harness = {
    hermesAgentEnabled = lib.mkOption {
      type    = lib.types.bool;
      default = false;
      description = "Enable Hermes Agent systemd service (NousResearch personal AI gateway).";
    };
    openClawEnabled = lib.mkOption {
      type    = lib.types.bool;
      default = false;
      description = "Enable OpenClaw systemd service (open-source self-hosted AI gateway, Hermes alternative). Added 7.30.0.";
    };
    tailscaleEnabled = lib.mkOption {
      type    = lib.types.bool;
      default = false;
      description = "When true, import services/tailscale.nix and the OCI Security List closes SSH port 22 (Tailscale becomes the only ingress).";
    };
  };

  # imports MUST be static — referencing `config.harness.*` here causes
  # infinite recursion (config needs imports, imports needs config). The
  # conditional services (hermes-agent / openclaw / tailscale) are always
  # imported but each wraps its body in `config = lib.mkIf config.harness.X {}`
  # so they are inert unless their option is true. cliproxyapi is always
  # active since 7.31.0 (dual-OAuth: daily-progress always routes through it).
  imports = [
    ./services/daily-progress.nix
    ./services/logrotate.nix
    ./services/security.nix
    ./services/cliproxyapi.nix
    ./services/hermes-agent.nix
    ./services/openclaw.nix
    ./services/tailscale.nix
  ];

  # All NixOS config attributes MUST live under `config` because this module
  # also declares top-level `options` (harness.*). Mixing bare config attrs
  # with `options` is rejected by the module system (nixpkgs lib/modules.nix).
  config = {
  # numtide's claude-code is packaged as unfree (binary source, Anthropic
  # licence); codex likewise. Allow ONLY the llm-agents agents we actually
  # ship — every other unfree package is still refused. Both the numtide
  # pname ("claude-code"/"codex") and the legacy self-built pname
  # ("openai-codex", pre-7.33.0) are whitelisted so the predicate is robust
  # regardless of which derivation lib.getName resolves.
  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (lib.getName pkg) [ "claude-code" "codex" "openai-codex" ];

  system.stateVersion = "25.05";

  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };
  boot.kernelPackages = pkgs.linuxPackages_latest;

  networking = {
    hostName = "harness-daily-progress";
    useDHCP = lib.mkForce true;
    firewall = {
      enable = true;
      allowedTCPPorts = [ 22 ];
    };
  };

  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";

  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
      # numtide binary cache — serves every pkgs.llm-agents.<name> prebuilt
      # for aarch64-linux so `nixos-rebuild` does NOT compile claude-code /
      # codex / cli-proxy-api / hermes-agent / openclaw from source. extra-*
      # (not the bare keys) so cache.nixos.org + the default trusted keys
      # are preserved alongside it.
      extra-substituters = [ "https://cache.numtide.com" ];
      extra-trusted-public-keys = [
        "niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g="
      ];
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };
  };

  users.users.opc = {
    isNormalUser = true;
    description = "Oracle Cloud default user";
    extraGroups = [ "wheel" ];
    shell = pkgs.bash;
    # Placeholder literal — setup-oci-vm-nixos.sh replaces this `keys`
    # entry with the real SSH public key at deploy time. Using a literal
    # `keys` (NOT `keyFiles` with an absolute path) keeps the flake
    # pure-eval clean so `nix flake check` can validate the whole config
    # without `--impure`. (7.32.0.1: was keyFiles=/etc/ssh/... which
    # broke pure eval and hid downstream bugs.)
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAREPLACEDBYSETUPOCIVMNIXOSSH placeholder@harness-replaced-at-deploy"
    ];
  };

  security.sudo.wheelNeedsPassword = false;

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
      X11Forwarding = false;
    };
  };

  environment.systemPackages = with pkgs; [
    curl jq gh git tmux htop vim ripgrep
    nodejs_20  # ad-hoc npm use (claude/codex now come from numtide, not npm -g)
    fzf        # fuzzy finder (history, files, branches)
    ghq        # GitHub repo manager (ghq get owner/repo)
    # CLI tools default set (7.33.0) — modern coreutils replacements that
    # make interactive SSH sessions actually pleasant.
    bat        # cat with syntax highlighting + git gutter
    eza        # ls replacement (tree, git status, icons)
    yq         # jq-for-YAML (config.yaml inspection)
    delta      # syntax-highlighting git diff/blame pager
    tldr       # concise community man-page examples
    # AI agents from numtide/llm-agents.nix (overlay in flake.nix).
    # binary: claude / codex. binary-cache hits, no from-source build.
    llm-agents.claude-code
    llm-agents.codex
  ];

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    users.opc = import ./home.nix;
  };
  };  # end config
}
