{ config, pkgs, lib, ... }:

let
  claude-code  = pkgs.callPackage ./pkgs/claude-code.nix { };   # added 7.29.2
  openai-codex = pkgs.callPackage ./pkgs/openai-codex.nix { };  # added 7.29.2
in
{
  # harness options — set via harness-overlay.nix (auto-generated by setup-oci-vm-nixos.sh).
  # harness.hermesAgentEnabled = true  → imports services/hermes-agent.nix
  # harness.openClawEnabled = true     → imports services/openclaw.nix (7.30.0)
  # harness.tailscaleEnabled = true    → imports services/tailscale.nix (7.32.0)
  # Exactly one of hermesAgentEnabled / openClawEnabled may be true (Q12.5 single-select).
  options.harness = {
    hermesAgentEnabled = lib.mkOption {
      type    = lib.types.bool;
      default = false;
      description = "Enable Hermes Agent systemd service (NousResearch personal AI gateway).";
    };
    openClawEnabled = lib.mkOption {
      type    = lib.types.bool;
      default = false;
      description = "Enable OpenClaw systemd service (open-source self-hosted AI gateway, Hermes alternative). Added 7.30.0.";
    };
    tailscaleEnabled = lib.mkOption {
      type    = lib.types.bool;
      default = false;
      description = "When true, import services/tailscale.nix and the OCI Security List closes SSH port 22 (Tailscale becomes the only ingress).";
    };
  };

  # imports MUST be static — referencing `config.harness.*` here causes
  # infinite recursion (config needs imports, imports needs config). The
  # conditional services (hermes-agent / openclaw / tailscale) are always
  # imported but each wraps its body in `config = lib.mkIf config.harness.X {}`
  # so they are inert unless their option is true. cliproxyapi is always
  # active since 7.31.0 (dual-OAuth: daily-progress always routes through it).
  imports = [
    ./services/daily-progress.nix
    ./services/logrotate.nix
    ./services/security.nix
    ./services/cliproxyapi.nix
    ./services/hermes-agent.nix
    ./services/openclaw.nix
    ./services/tailscale.nix
  ];

  # All NixOS config attributes MUST live under `config` because this module
  # also declares top-level `options` (harness.*). Mixing bare config attrs
  # with `options` is rejected by the module system (nixpkgs lib/modules.nix).
  config = {
  # claude-code / openai-codex CLIs are proprietary (licenses.unfree in
  # pkgs/*.nix). Allow ONLY those two — every other unfree package is
  # still refused. (7.29.2 added the derivations; 7.32.0.1 wires the
  # predicate so nixos-rebuild can actually evaluate them.)
  nixpkgs.config.allowUnfreePredicate = pkg:
    builtins.elem (lib.getName pkg) [ "claude-code" "openai-codex" ];

  system.stateVersion = "25.05";

  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };
  boot.kernelPackages = pkgs.linuxPackages_latest;

  networking = {
    hostName = "harness-daily-progress";
    useDHCP = lib.mkForce true;
    firewall = {
      enable = true;
      allowedTCPPorts = [ 22 ];
    };
  };

  time.timeZone = "UTC";
  i18n.defaultLocale = "en_US.UTF-8";

  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      auto-optimise-store = true;
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };
  };

  users.users.opc = {
    isNormalUser = true;
    description = "Oracle Cloud default user";
    extraGroups = [ "wheel" ];
    shell = pkgs.bash;
    # Placeholder literal — setup-oci-vm-nixos.sh replaces this `keys`
    # entry with the real SSH public key at deploy time. Using a literal
    # `keys` (NOT `keyFiles` with an absolute path) keeps the flake
    # pure-eval clean so `nix flake check` can validate the whole config
    # without `--impure`. (7.32.0.1: was keyFiles=/etc/ssh/... which
    # broke pure eval and hid downstream bugs.)
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAREPLACEDBYSETUPOCIVMNIXOSSH placeholder@harness-replaced-at-deploy"
    ];
  };

  security.sudo.wheelNeedsPassword = false;

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
      X11Forwarding = false;
    };
  };

  environment.systemPackages = with pkgs; [
    curl jq gh git tmux htop vim ripgrep
    nodejs_20  # runtime dependency for claude / codex (and ad-hoc npm use)
    fzf        # fuzzy finder (history, files, branches)
    ghq        # GitHub repo manager (ghq get owner/repo)
  ] ++ [
    claude-code   # Anthropic Claude Code CLI — buildNpmPackage derivation (added 7.29.2)
    openai-codex  # OpenAI Codex CLI        — buildNpmPackage derivation (added 7.29.2)
  ];

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    users.opc = import ./home.nix;
  };
  };  # end config
}
