#!/usr/bin/env bash
# architecture-diagram.sh — dev/src/ の import 関係から Mermaid 図を生成する。
# Clean Architecture の層別 (interfaces / application / domain / infrastructure) に
# クラスタリングし、依存方向違反を視覚化する。
#
# Output:
#   dev/docs/architecture.mmd      (Mermaid)
#   dev/docs/architecture-meta.json (件数 + 違反リスト)
#
# Usage:
#   bash scripts/architecture-diagram.sh
#
# CI 用ワークフロー (templates/github/workflows/architecture-diagram.yml) が
# PR 時に走り、図を最新化してコミットする。

set -u

__resolve_root() {
  local d="${1:-$PWD}"
  while [ "$d" != "/" ]; do
    [ -d "$d/.bare" ] && { echo "$d"; return 0; }
    d="$(dirname "$d")"
  done
  echo "${1:-$PWD}"
}
ROOT="$(__resolve_root "$PWD")"
SRC="$ROOT/dev/src"
OUT_MMD="$ROOT/dev/docs/architecture.mmd"
OUT_META="$ROOT/dev/docs/architecture-meta.json"

[ -d "$SRC" ] || { echo "no $SRC" >&2; exit 1; }
mkdir -p "$(dirname "$OUT_MMD")"

# 1) 全 ts ファイル列挙 (test 除く)
FILES=$(find "$SRC" -type f \( -name '*.ts' -o -name '*.tsx' \) ! -name '*.test.ts' ! -name '*.spec.ts')

layer_of() {
  case "$1" in
    */interfaces/*)     echo interfaces ;;
    */application/*)    echo application ;;
    */domain/*)         echo domain ;;
    */infrastructure/*) echo infrastructure ;;
    *)                  echo other ;;
  esac
}

# 2) ノード + import エッジを抽出
{
  echo "%% Auto-generated by scripts/architecture-diagram.sh — do not edit by hand"
  echo "%% Layer rule: domain ← application ← (interfaces | infrastructure)"
  echo "graph LR"
  echo "  classDef interfaces     fill:#e3f2fd,stroke:#1976d2"
  echo "  classDef application    fill:#e8f5e9,stroke:#388e3c"
  echo "  classDef domain         fill:#fffde7,stroke:#fbc02d"
  echo "  classDef infrastructure fill:#fce4ec,stroke:#c2185b"
} > "$OUT_MMD"

declare_node() {
  local f="$1" rel layer id
  rel="${f#$SRC/}"
  layer=$(layer_of "$f")
  id=$(echo "$rel" | tr '/.' '__')
  printf '  %s["%s"]:::%s\n' "$id" "$rel" "$layer" >> "$OUT_MMD"
}

violations=0
violations_list=()

emit_edge() {
  local from_id="$1" to_id="$2" from_layer="$3" to_layer="$4"
  printf '  %s --> %s\n' "$from_id" "$to_id" >> "$OUT_MMD"
  # Clean Arch 違反: domain → application / interfaces / infrastructure はダメ
  if [ "$from_layer" = "domain" ] && [ "$to_layer" != "domain" ]; then
    violations=$(( violations + 1 ))
    violations_list+=("$from_id → $to_id ($from_layer → $to_layer)")
  fi
  # application → interfaces もダメ
  if [ "$from_layer" = "application" ] && [ "$to_layer" = "interfaces" ]; then
    violations=$(( violations + 1 ))
    violations_list+=("$from_id → $to_id (application → interfaces)")
  fi
}

# ノード宣言
while IFS= read -r f; do
  [ -n "$f" ] && declare_node "$f"
done <<< "$FILES"

# エッジ抽出 (相対 import のみ追跡)
while IFS= read -r f; do
  [ -n "$f" ] || continue
  from_rel="${f#$SRC/}"
  from_id=$(echo "$from_rel" | tr '/.' '__')
  from_layer=$(layer_of "$f")
  from_dir=$(dirname "$f")

  imports=$(grep -E "^import .* from '(\\./|\\.\\./)" "$f" 2>/dev/null \
    | sed -E "s/.*from ['\"]([^'\"]+)['\"].*/\1/")

  while IFS= read -r imp; do
    [ -n "$imp" ] || continue
    target=$(cd "$from_dir" 2>/dev/null && pwd)/$(echo "$imp" | sed 's|^\./||')
    # .ts 補完
    for ext in '' '.ts' '.tsx' '/index.ts'; do
      if [ -f "${target}${ext}" ]; then
        target="${target}${ext}"
        break
      fi
    done
    [ -f "$target" ] || continue
    to_rel="${target#$SRC/}"
    to_id=$(echo "$to_rel" | tr '/.' '__')
    to_layer=$(layer_of "$target")
    emit_edge "$from_id" "$to_id" "$from_layer" "$to_layer"
  done <<< "$imports"
done <<< "$FILES"

# meta JSON
node_count=$(echo "$FILES" | grep -c .)
{
  printf '{\n'
  printf '  "generated_at": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '  "node_count": %d,\n' "$node_count"
  printf '  "violations": %d,\n' "$violations"
  printf '  "violation_list": ['
  first=1
  for v in "${violations_list[@]}"; do
    [ $first -eq 0 ] && printf ', '
    first=0
    printf '"%s"' "$(echo "$v" | sed 's/"/\\"/g')"
  done
  printf ']\n'
  printf '}\n'
} > "$OUT_META"

echo "architecture diagram: $OUT_MMD"
echo "meta: $OUT_META ($node_count nodes, $violations violations)"
[ "$violations" -gt 0 ] && exit 2 || exit 0
