#!/usr/bin/env bash
# ensure-claude-oauth-token.sh — capture or refresh the project's
# Claude Code OAuth token (= the subscription-bound token generated by
# `claude setup-token` on a desktop machine).
#
# This is the SAME token GitHub's claude-code-action consumes via
# `${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}`, and the SAME token the OCI
# VM's daily-progress bot consumes via the `CLAUDE_CODE_OAUTH_TOKEN`
# environment variable. One token, two consumers.
#
# Token characteristics (per code.claude.com/docs/en/iam):
#   - Lifetime: ~1 year (Anthropic's "long-lived token" for CI/scripts).
#   - Refresh:  none required — the token is self-contained.
#   - Storage:  the user copy/pastes the value once; we save it here.
#   - Revoke:   regenerate with `claude setup-token` (the old one stays
#               valid until naturally expiring unless the user logs out
#               of Claude entirely).
#
# Persists to <root>/.my-harness/.notification.env (same file as the
# webhook URL + GH_TOKEN — single gitignored secrets bundle for the
# notification / VM pipeline). Adds:
#
#   CLAUDE_CODE_OAUTH_TOKEN=<token>
#
# Usage:
#   bash ensure-claude-oauth-token.sh <root> [<existing-token>]
#
# If <existing-token> is empty, the script exits 3 to signal the caller
# (SKILL.md) to AskUserQuestion for it. The caller should walk the user
# through running `claude setup-token` on their desktop machine and
# pasting the printed value back.

set -u

ROOT="${1:?root required}"
PROVIDED_TOKEN="${2:-}"

# Lightweight shape validation. Anthropic has not committed to a stable
# token prefix in public docs, so we only check that the value looks
# plausibly token-like (no whitespace, no leading dash, sufficient
# length, allowed alphabet) rather than a hardcoded prefix that would
# break if it ever changed.
validate_token() {
  local tok="$1"
  if [ ${#tok} -lt 30 ]; then
    echo "::error:: token looks too short (length ${#tok}). claude setup-token output is typically 60+ characters." >&2
    return 1
  fi
  if [[ "$tok" =~ [[:space:]] ]]; then
    echo "::error:: token contains whitespace. Make sure you pasted only the token line, no surrounding text." >&2
    return 1
  fi
  if [[ ! "$tok" =~ ^[A-Za-z0-9_=+/.~-]+$ ]]; then
    echo "::error:: token contains unexpected characters. Re-run \`claude setup-token\` and copy only the printed value." >&2
    return 1
  fi
  return 0
}

mkdir -p "$ROOT/.my-harness"
OUT="$ROOT/.my-harness/.notification.env"

if [ -z "$PROVIDED_TOKEN" ]; then
  echo "::error:: no Claude OAuth token provided." >&2
  echo "  Caller (SKILL.md) should:" >&2
  echo "    1. Instruct the user to run \`claude setup-token\` on their desktop machine." >&2
  echo "    2. AskUserQuestion to capture the printed token value." >&2
  echo "    3. Re-invoke this script with the token as arg 2." >&2
  exit 3
fi

validate_token "$PROVIDED_TOKEN" || exit 2

# Append or update CLAUDE_CODE_OAUTH_TOKEN line in the same file as the
# webhook URL + GH_TOKEN. Strip any prior CLAUDE_CODE_OAUTH_TOKEN= line
# and re-append — same merge pattern as ensure-github-pat.sh.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
if [ -f "$OUT" ]; then
  grep -v '^CLAUDE_CODE_OAUTH_TOKEN=' "$OUT" > "$TMP" || true
fi
{
  cat "$TMP"
  echo "CLAUDE_CODE_OAUTH_TOKEN=$PROVIDED_TOKEN"
} > "$OUT"
chmod 600 "$OUT"

echo "[claude-oauth-token] saved CLAUDE_CODE_OAUTH_TOKEN to $OUT (length ${#PROVIDED_TOKEN}, ~1 year lifetime)"
