#!/usr/bin/env bash
# Summary: One-shot installer for RTK (Rust Token Killer) — Phase 1 of the
#          context-pressure mitigation plan. RTK is a PreToolUse hook for
#          Claude Code that compresses Bash output (git/ls/grep/test runners…)
#          by 60-90% before it lands in Claude's context window.
#
#          This script:
#            1. Installs `rtk` via Homebrew (macOS) or cargo (fallback)
#            2. Runs `rtk init -g` to register the global PreToolUse hook
#            3. Patches ~/.config/rtk/config.toml so my-harness wrappers
#               (codex / codex-ask.sh / claude) are NEVER rewritten — their
#               output IS the assistant's reply and must not be touched.
#
# Usage:
#   bash scripts/install-rtk.sh              # install + configure
#   bash scripts/install-rtk.sh --check      # verify install + config only
#   bash scripts/install-rtk.sh --uninstall  # uninstall (best-effort)

set -euo pipefail

CHECK_ONLY=0
UNINSTALL=0
case "${1:-}" in
  --check) CHECK_ONLY=1 ;;
  --uninstall) UNINSTALL=1 ;;
  --help|-h)
    sed -n '1,/^set -euo pipefail/p' "$0" | sed 's/^# \?//'
    exit 0
    ;;
  "") ;;
  *) echo "::error:: unknown flag: $1" >&2; exit 2 ;;
esac

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/rtk"
CONFIG_FILE="$CONFIG_DIR/config.toml"

# Commands whose output must reach Claude verbatim. Touching them would corrupt
# the Codex bridge and Claude Code's own self-invocations.
EXCLUDE_COMMANDS=("codex" "codex-ask.sh" "claude")

ensure_rtk_installed() {
  if command -v rtk >/dev/null 2>&1; then
    echo "[install-rtk] rtk found: $(command -v rtk)"
    rtk --version 2>/dev/null || true
    return 0
  fi
  if [ "$CHECK_ONLY" -eq 1 ]; then
    echo "::error:: rtk not installed (run without --check to install)" >&2
    exit 1
  fi
  if command -v brew >/dev/null 2>&1; then
    echo "[install-rtk] installing via Homebrew…"
    brew install rtk
  elif command -v cargo >/dev/null 2>&1; then
    echo "[install-rtk] installing via cargo (Homebrew not found)…"
    cargo install rtk-cli
  else
    echo "::error:: neither brew nor cargo found. Install one, then re-run." >&2
    echo "  Manual install: https://github.com/rtk-ai/rtk" >&2
    exit 1
  fi
}

run_init() {
  if [ "$CHECK_ONLY" -eq 1 ] || [ "$UNINSTALL" -eq 1 ]; then return 0; fi
  local settings="$HOME/.claude/settings.json"
  if [ -f "$settings" ]; then
    local backup="$settings.pre-rtk.$(date +%Y%m%d%H%M%S).bak"
    cp "$settings" "$backup"
    echo "[install-rtk] backed up settings.json to $backup"
  fi
  echo "[install-rtk] running \`rtk init -g --auto-patch\` (registers PreToolUse hook)…"
  rtk init -g --auto-patch
}

write_config() {
  if [ "$CHECK_ONLY" -eq 1 ] || [ "$UNINSTALL" -eq 1 ]; then return 0; fi
  mkdir -p "$CONFIG_DIR"
  # Skip if EITHER `[hooks]` section OR `exclude_commands` key already exists.
  # The double check matters: if a user (or a future RTK release) wrote a
  # bare `[hooks]` section without our exclude key, blindly appending another
  # one produces a TOML duplicate-section error.
  if [ -f "$CONFIG_FILE" ] && grep -qE "^\[hooks\]|exclude_commands" "$CONFIG_FILE"; then
    echo "[install-rtk] $CONFIG_FILE already has [hooks]/exclude_commands; leaving it alone."
    echo "  Verify the following commands are excluded (edit the file by hand if not):"
    printf "    - %s\n" "${EXCLUDE_COMMANDS[@]}"
    return 0
  fi
  {
    echo "# Generated by my-harness-generator/scripts/install-rtk.sh"
    echo "# Excluding commands whose output is part of an assistant's reply, not"
    echo "# something we want compressed before it reaches Claude."
    echo "[hooks]"
    printf 'exclude_commands = ['
    sep=""
    for c in "${EXCLUDE_COMMANDS[@]}"; do
      printf '%s"%s"' "$sep" "$c"
      sep=", "
    done
    printf ']\n'
  } >> "$CONFIG_FILE"
  echo "[install-rtk] appended exclude_commands to $CONFIG_FILE"
}

verify_config() {
  if [ ! -f "$CONFIG_FILE" ]; then
    echo "::warning:: $CONFIG_FILE not found"
    return 1
  fi
  echo "[install-rtk] active config:"
  cat "$CONFIG_FILE"
}

uninstall_rtk() {
  if ! command -v rtk >/dev/null 2>&1; then
    echo "[install-rtk] rtk not present; nothing to remove"
    return 0
  fi
  if command -v brew >/dev/null 2>&1 && brew list rtk >/dev/null 2>&1; then
    brew uninstall rtk
  elif command -v cargo >/dev/null 2>&1; then
    cargo uninstall rtk-cli || true
  fi
  if [ -d "$CONFIG_DIR" ]; then
    echo "[install-rtk] keeping $CONFIG_DIR (delete manually if you want a clean slate)"
  fi
  echo "[install-rtk] hook entry in ~/.claude/settings.json may need manual removal"
}

if [ "$UNINSTALL" -eq 1 ]; then
  uninstall_rtk
  exit 0
fi

ensure_rtk_installed
run_init
write_config
verify_config
echo
echo "[install-rtk] done. Restart Claude Code to pick up the new PreToolUse hook."
