#!/usr/bin/env bash
# setup-oci-vm-nixos.sh — deploy NixOS to an Oracle Cloud Always-Free
# A1.Flex VM via nixos-anywhere, then deploy daily-progress bot.
#
# This is the NixOS counterpart to setup-oci-vm.sh (Oracle Linux 9).
# Both honor the same .my-harness/.notification.env + .my-harness/.oci-vm.env
# conventions and produce the same end-state (daily-progress bot running
# on a schedule, posting to Discord/Slack/Teams), but via systemd timers
# and declarative configuration instead of cron + dnf.
#
# Prerequisites on the Mac:
#   - nix command (https://nixos.org/download.html or DetSys installer)
#   - .my-harness/.notification.env populated (Phase 1 Q6-Q11)
#   - .my-harness/.oci-vm.env populated (Q9)
#   - SSH key from .oci-vm.env can reach opc@$OCI_VM_PUBLIC_IP
#   - The VM currently runs Oracle Linux or Ubuntu (any kexec-able OS)
#
# What this script does:
#   1. Loads .notification.env + .oci-vm.env
#   2. Stages templates/oracle-cloud/nixos/ to a temp dir
#   3. Injects the user's SSH public key into a temp authorized_keys file
#   4. Runs `nix run github:nix-community/nixos-anywhere` to kexec the
#      existing OS to the NixOS installer, disk re-partitioned via disko,
#      NixOS installed, reboot
#   5. Waits for SSH to come back on the same IP
#   6. scp's templates/oracle-cloud/daily-progress-bot/ → /home/opc/
#   7. Writes /home/opc/daily-progress-bot/.env from .notification.env
#   8. If AI_PROVIDER=codex, scp's .my-harness/.codex-auth.json
#   9. systemctl enable --now daily-progress.timer event-watch.timer
#  10. Triggers daily-progress.service once as a smoke test
#  11. Prints success summary

set -u

ROOT="${1:?root required (path to project root containing .my-harness/)}"

trap 'rc=$?; if [ $rc -ne 0 ]; then echo "::error:: setup-oci-vm-nixos.sh failed at line $LINENO (exit $rc)" >&2; fi' EXIT

NOTIF_FILE="$ROOT/.my-harness/.notification.env"
OCI_FILE="$ROOT/.my-harness/.oci-vm.env"
[ -f "$NOTIF_FILE" ] || { echo "::error:: $NOTIF_FILE missing — run Phase 1 Q6-Q11 first" >&2; exit 1; }
[ -f "$OCI_FILE" ] || { echo "::error:: $OCI_FILE missing — run ensure-oci-vm.sh first" >&2; exit 1; }

set -a
# shellcheck disable=SC1090
. "$NOTIF_FILE"
# shellcheck disable=SC1090
. "$OCI_FILE"
set +a

: "${AI_PROVIDER:=claude}"
case "$AI_PROVIDER" in
  claude|codex) : ;;
  *) echo "::error:: unknown AI_PROVIDER='$AI_PROVIDER' (daily-progress bot provider)" >&2; exit 1 ;;
esac

REQUIRED=(NOTIFICATION_SERVICE NOTIFICATION_WEBHOOK_URL GH_TOKEN \
          OCI_VM_NAME OCI_VM_REGION OCI_VM_PUBLIC_IP OCI_VM_SSH_KEY)
[ "$AI_PROVIDER" = "claude" ] && REQUIRED+=(CLAUDE_CODE_OAUTH_TOKEN)

missing=()
for v in "${REQUIRED[@]}"; do
  eval "val=\${$v:-}"
  [ -n "$val" ] || missing+=("$v")
done
if [ "${#missing[@]}" -gt 0 ]; then
  echo "::error:: missing required env: ${missing[*]}" >&2
  exit 1
fi

# Expand ~
case "$OCI_VM_SSH_KEY" in "~/"*) OCI_VM_SSH_KEY="$HOME/${OCI_VM_SSH_KEY#~/}" ;; esac

PUB_KEY_FILE="${OCI_VM_SSH_KEY}.pub"
[ -f "$PUB_KEY_FILE" ] || { echo "::error:: SSH public key $PUB_KEY_FILE not found" >&2; exit 1; }

command -v nix >/dev/null 2>&1 || {
  echo "::error:: nix command not on PATH. Install Nix on this Mac first:" >&2
  echo "  curl -L https://nixos.org/nix/install | sh" >&2
  exit 1
}

HARNESS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
NIXOS_SRC="$HARNESS_DIR/templates/oracle-cloud/nixos"
[ -d "$NIXOS_SRC" ] || { echo "::error:: $NIXOS_SRC not found — harness layout broken" >&2; exit 1; }

# Stage NixOS config to a temp dir we can modify (injecting authorized_keys)
STAGE_DIR="$(mktemp -d)"
trap 'rm -rf "$STAGE_DIR"' EXIT
cp -r "$NIXOS_SRC"/. "$STAGE_DIR"/

# Inline the SSH public key directly into configuration.nix
PUB_KEY_CONTENT=$(cat "$PUB_KEY_FILE")
python3 - <<PYEOF
import re, sys
src = open("$STAGE_DIR/configuration.nix").read()
new = re.sub(
    r'openssh\.authorizedKeys\.keyFiles\s*=\s*\[[^\]]*\]\s*;',
    'openssh.authorizedKeys.keys = [ "$PUB_KEY_CONTENT" ];',
    src,
    count=1
)
open("$STAGE_DIR/configuration.nix", "w").write(new)
PYEOF

# When Hermes is enabled, write a harness-overlay.nix that sets
# harness.hermesAgentEnabled = true so the NixOS module disables the shell-cron
# timers (daily-progress.timer + event-watch.timer) at the declarative level.
if [ "${HERMES_AGENT_ENABLED:-no}" = "yes" ]; then
  cat > "$STAGE_DIR/harness-overlay.nix" <<'OVERLAY_NIX'
# Auto-generated by setup-oci-vm-nixos.sh when HERMES_AGENT_ENABLED=yes.
# Sets harness.hermesAgentEnabled = true so daily-progress.timer and
# event-watch.timer stay disabled — Hermes Agent's internal cron handles
# the daily report instead (session daily-report-<repo>, 09:00 UTC).
{ ... }: { harness.hermesAgentEnabled = true; }
OVERLAY_NIX

  # Inject the overlay import into configuration.nix so nixos-anywhere picks it up.
  python3 - <<PYEOF
src = open("$STAGE_DIR/configuration.nix").read()
# Insert ./harness-overlay.nix into the imports list after the first import entry.
import re
new = re.sub(
    r'(imports\s*=\s*\[)',
    r'\1\n    ./harness-overlay.nix',
    src,
    count=1
)
open("$STAGE_DIR/configuration.nix", "w").write(new)
PYEOF
  echo "[setup-vm-nixos] harness-overlay.nix written: harness.hermesAgentEnabled = true"
fi

SSH_TARGET="opc@$OCI_VM_PUBLIC_IP"
SSH_OPTS=(-o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new -i "$OCI_VM_SSH_KEY")

echo "[setup-vm-nixos] testing SSH to $SSH_TARGET..."
ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "echo ok" 2>/dev/null | grep -q ok || {
  echo "::error:: cannot SSH to $SSH_TARGET; check VM running + key matches" >&2
  exit 2
}

echo "[setup-vm-nixos] running nixos-anywhere — this kexec's the existing OS to NixOS installer."
echo "                 disk will be re-partitioned via disko. existing data is LOST."
echo "                 (If you have data on this VM you need to keep, abort now: Ctrl-C)"
sleep 5

# nixos-anywhere expects to SSH as root. opc has wheel + NOPASSWD sudo.
nix run github:nix-community/nixos-anywhere -- \
  --flake "$STAGE_DIR#harness-daily-progress" \
  --target-host "root@${OCI_VM_PUBLIC_IP}" \
  --ssh-option "IdentityFile=$OCI_VM_SSH_KEY" \
  --ssh-option "StrictHostKeyChecking=accept-new" \
  || {
  echo "::error:: nixos-anywhere failed" >&2
  exit 3
}

echo "[setup-vm-nixos] NixOS installation complete, waiting for SSH to come back..."

# Strip old host key (NixOS will have a new one)
ssh-keygen -R "$OCI_VM_PUBLIC_IP" 2>/dev/null || true

# Wait up to 10 minutes for SSH to return
for i in $(seq 1 60); do
  if ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new -i "$OCI_VM_SSH_KEY" \
        "$SSH_TARGET" "echo ok" 2>/dev/null | grep -q ok; then
    echo "[setup-vm-nixos] SSH back up after $((i*10))s"
    break
  fi
  [ "$i" -eq 60 ] && { echo "::error:: SSH didn't come back within 10 min" >&2; exit 4; }
  sleep 10
done

# Deploy daily-progress-bot files
LOCAL_BOT="$HARNESS_DIR/templates/oracle-cloud/daily-progress-bot"
echo "[setup-vm-nixos] copying daily-progress-bot to /home/opc/..."
ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "mkdir -p ~/daily-progress-bot && chmod 700 ~/daily-progress-bot"
scp -r -i "$OCI_VM_SSH_KEY" "$LOCAL_BOT"/. "$SSH_TARGET:~/daily-progress-bot/"
ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "chmod +x ~/daily-progress-bot/*.sh"

# Derive repo owner/name
if ! GIT_REMOTE_URL="$(git -C "$ROOT" remote get-url origin 2>/dev/null)"; then
  echo "::error:: no 'origin' git remote at $ROOT" >&2
  exit 5
fi
REPO_SLUG="$(echo "$GIT_REMOTE_URL" | sed -e 's|^git@github\.com:||' -e 's|^https://github\.com/||' -e 's|\.git$||')"
REPO_OWNER="${REPO_SLUG%%/*}"
REPO_NAME="${REPO_SLUG#*/}"

# Provider-specific install (claude / codex on top of node from system pkgs)
case "$AI_PROVIDER" in
  claude)
    ssh "${SSH_OPTS[@]}" "$SSH_TARGET" 'bash -lc "mkdir -p ~/.npm-global && npm config set prefix ~/.npm-global && npm install -g @anthropic-ai/claude-code"'
    ;;
  codex)
    ssh "${SSH_OPTS[@]}" "$SSH_TARGET" 'bash -lc "mkdir -p ~/.npm-global ~/.codex && npm config set prefix ~/.npm-global && npm install -g @openai/codex"'
    CODEX_AUTH="$ROOT/.my-harness/.codex-auth.json"
    [ -f "$CODEX_AUTH" ] || bash "$HARNESS_DIR/scripts/ensure-codex-auth.sh" "$ROOT"
    scp -q -i "$OCI_VM_SSH_KEY" "$CODEX_AUTH" "$SSH_TARGET:~/.codex/auth.json"
    ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "chmod 600 ~/.codex/auth.json"
    ;;
esac

# Write .env on the VM
CLAUDE_TOKEN="${CLAUDE_CODE_OAUTH_TOKEN:-}"
ssh "${SSH_OPTS[@]}" "$SSH_TARGET" 'bash -s' <<REMOTE_ENV
set -eu
umask 077
cat > "\$HOME/daily-progress-bot/.env" <<EOF
# Auto-written by scripts/setup-oci-vm-nixos.sh on \$(date -u +%Y-%m-%dT%H:%M:%SZ)
AI_PROVIDER=$AI_PROVIDER
$([ "$AI_PROVIDER" = "claude" ] && echo "CLAUDE_CODE_OAUTH_TOKEN=$CLAUDE_TOKEN")
NOTIFICATION_SERVICE=$NOTIFICATION_SERVICE
NOTIFICATION_WEBHOOK_URL=$NOTIFICATION_WEBHOOK_URL
GH_TOKEN=$GH_TOKEN
REPO_OWNER=$REPO_OWNER
REPO_NAME=$REPO_NAME
LANG_TAG=ja
LOOKBACK_HOURS=24
EOF
chmod 600 "\$HOME/daily-progress-bot/.env"
REMOTE_ENV

# -----------------------------------------------------------------------------
# Hermes Agent deploy (optional — gated on HERMES_AGENT_ENABLED=yes)
# Set in .notification.env by /my-harness-init Q12.5.
# Supports 4 AI providers: codex | claude-code | openrouter | claude-api
# codex + claude-code route through CLIProxyAPI (localhost:8317).
# openrouter + claude-api connect directly with their respective API keys.
# -----------------------------------------------------------------------------
if [ "${HERMES_AGENT_ENABLED:-no}" = "yes" ]; then
  echo "[setup-vm-nixos] deploying Hermes Agent..."

  HERMES_CONFIG="$ROOT/.my-harness/.hermes-config.json"
  [ -f "$HERMES_CONFIG" ] || {
    echo "::error:: $HERMES_CONFIG missing — run scripts/ensure-hermes-config.sh first" >&2
    exit 1
  }

  # Read values from the JSON config.
  HERMES_BOT_TOKEN="$(python3 -c "import json; d=json.load(open('$HERMES_CONFIG')); print(d['DISCORD_BOT_TOKEN'])")"
  HERMES_AI_PROVIDER="$(python3 -c "import json; d=json.load(open('$HERMES_CONFIG')); print(d['ai_provider'])")"
  HERMES_BASE_URL="$(python3 -c "import json; d=json.load(open('$HERMES_CONFIG')); print(d.get('OPENAI_BASE_URL',''))")"
  HERMES_MODEL="$(python3 -c "import json; d=json.load(open('$HERMES_CONFIG')); print(d['OPENAI_MODEL'])")"
  HERMES_OPENROUTER_KEY="$(python3 -c "import json; d=json.load(open('$HERMES_CONFIG')); print(d.get('openrouter_api_key') or '')")"
  HERMES_ANTHROPIC_KEY="$(python3 -c "import json; d=json.load(open('$HERMES_CONFIG')); print(d.get('anthropic_api_key') or '')")"
  DISCORD_HOME_CHANNEL_NAME="$(python3 -c "import json; d=json.load(open('$HERMES_CONFIG')); print(d.get('discord',{}).get('home_channel_name',''))")"
  DISCORD_APP_CHANNEL_NAME="$(python3 -c "import json; d=json.load(open('$HERMES_CONFIG')); print(d.get('discord',{}).get('app_channel_name',''))")"

  case "$HERMES_AI_PROVIDER" in
    codex|claude-code|openrouter|claude-api) : ;;
    *)
      echo "::error:: Unsupported HERMES_AI_PROVIDER='$HERMES_AI_PROVIDER' in $HERMES_CONFIG" >&2
      echo "  Valid values: codex | claude-code | openrouter | claude-api" >&2
      echo "  Re-run scripts/ensure-hermes-config.sh to update." >&2
      exit 1
      ;;
  esac

  # Build the provider YAML stanza that replaces ${HERMES_PROVIDER_BLOCK}.
  case "$HERMES_AI_PROVIDER" in
    codex)
      HERMES_PROVIDER_BLOCK="model:
  provider: custom
  default: hermes-codex-default
  base_url: http://localhost:8317/v1
  api_key: \"\""
      ;;
    claude-code)
      HERMES_PROVIDER_BLOCK="model:
  provider: custom
  default: hermes-claude-default
  base_url: http://localhost:8317/v1
  api_key: \"\""
      ;;
    openrouter)
      HERMES_PROVIDER_BLOCK="model:
  provider: openrouter
  default: anthropic/claude-sonnet-4
  # OPENROUTER_API_KEY is injected via .env (EnvironmentFile)"
      ;;
    claude-api)
      HERMES_PROVIDER_BLOCK="model:
  provider: anthropic
  default: claude-sonnet-4-6
  # ANTHROPIC_API_KEY is injected via .env (EnvironmentFile)"
      ;;
  esac

  # Create directory structure on VM.
  ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "mkdir -p ~/hermes-agent/data && chmod 750 ~/hermes-agent"

  # Deploy CLIProxyAPI config + auth when needed (codex or claude-code provider).
  # 7.29.0: The CLIProxyAPI binary is now built by NixOS via pkgs/cliproxyapi.nix
  # (buildGoModule). nixos-rebuild switch installs it into /nix/store and enables
  # cliproxyapi.service via wantedBy = [ "multi-user.target" ] — no manual
  # systemctl enable or tarball download needed here.
  if [ "$HERMES_AI_PROVIDER" = "codex" ] || [ "$HERMES_AI_PROVIDER" = "claude-code" ]; then
    echo "[setup-vm-nixos] deploying CLIProxyAPI config for provider=$HERMES_AI_PROVIDER (binary built by NixOS)..."

    # Render cliproxyapi/config.example.yaml with provider enable/disable flags.
    CLIPROXY_TMPL="$HARNESS_DIR/templates/oracle-cloud/cliproxyapi/config.example.yaml"
    RENDERED_CLIPROXY="$(mktemp /tmp/cliproxy-config-XXXXXX.yaml)"
    python3 - <<PYEOF
with open("$CLIPROXY_TMPL") as f:
    content = f.read()

enable_codex       = "$HERMES_AI_PROVIDER" == "codex"
enable_claude_code = "$HERMES_AI_PROVIDER" == "claude-code"

# Substitute per-provider exclusion placeholders.
# When a provider is disabled, exclude all its models via wildcard.
codex_excluded   = "" if enable_codex       else "- \"*\""
claude_excluded  = "" if enable_claude_code else "- \"*\""

content = content.replace("\${CODEX_EXCLUDED}",  codex_excluded)
content = content.replace("\${CLAUDE_EXCLUDED}", claude_excluded)

with open("$RENDERED_CLIPROXY", "w") as f:
    f.write(content)
PYEOF

    # The tmpfiles.rules d-entry in cliproxyapi.nix creates this dir on first boot,
    # but create it here too so scp works before the first nixos-rebuild.
    ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "mkdir -p ~/cliproxyapi && chmod 750 ~/cliproxyapi"
    scp -q -i "$OCI_VM_SSH_KEY" "$RENDERED_CLIPROXY" "$SSH_TARGET:~/cliproxyapi/config.yaml"
    ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "chmod 600 ~/cliproxyapi/config.yaml"
    rm -f "$RENDERED_CLIPROXY"

    # Deploy Codex auth.json when provider=codex.
    if [ "$HERMES_AI_PROVIDER" = "codex" ]; then
      CODEX_AUTH="$ROOT/.my-harness/.codex-auth.json"
      [ -f "$CODEX_AUTH" ] || bash "$HARNESS_DIR/scripts/ensure-codex-auth.sh" "$ROOT"
      scp -q -i "$OCI_VM_SSH_KEY" "$CODEX_AUTH" "$SSH_TARGET:~/.codex/auth.json"
      ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "chmod 600 ~/.codex/auth.json"
    fi

    echo "[setup-vm-nixos] CLIProxyAPI config deployed (service managed by NixOS — started by nixos-rebuild)."
  fi

  # Render config.example.yaml → config.yaml (substitute placeholders).
  HERMES_TMPL="$HARNESS_DIR/templates/oracle-cloud/hermes-agent/config.example.yaml"
  RENDERED_CONFIG="$(mktemp /tmp/hermes-config-XXXXXX.yaml)"
  python3 - <<PYEOF
with open("$HERMES_TMPL") as f:
    content = f.read()

replacements = {
    "\${HERMES_PROVIDER_BLOCK}":    """$HERMES_PROVIDER_BLOCK""",
    "\${DISCORD_BOT_TOKEN}":        "$HERMES_BOT_TOKEN",
    "\${DISCORD_HOME_CHANNEL_NAME}":"$DISCORD_HOME_CHANNEL_NAME",
    "\${DISCORD_APP_CHANNEL_NAME}": "$DISCORD_APP_CHANNEL_NAME",
}
for k, v in replacements.items():
    content = content.replace(k, v)

with open("$RENDERED_CONFIG", "w") as f:
    f.write(content)
PYEOF

  scp -q -i "$OCI_VM_SSH_KEY" "$RENDERED_CONFIG" "$SSH_TARGET:~/hermes-agent/config.yaml"
  ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "chmod 600 ~/hermes-agent/config.yaml"
  rm -f "$RENDERED_CONFIG"

  # Write the .env on the VM (read by hermes-agent.service via EnvironmentFile).
  ssh "${SSH_OPTS[@]}" "$SSH_TARGET" 'bash -s' <<REMOTE_HERMES_ENV
set -eu
umask 077
{
  echo "# Auto-written by scripts/setup-oci-vm-nixos.sh — do not edit by hand."
  echo "DISCORD_BOT_TOKEN=$HERMES_BOT_TOKEN"
  echo "HERMES_AI_PROVIDER=$HERMES_AI_PROVIDER"
  echo "OPENAI_MODEL=$HERMES_MODEL"
  echo "DISCORD_HOME_CHANNEL_NAME=$DISCORD_HOME_CHANNEL_NAME"
  echo "DISCORD_APP_CHANNEL_NAME=$DISCORD_APP_CHANNEL_NAME"
$([ -n "$HERMES_OPENROUTER_KEY" ] && echo "  echo \"OPENROUTER_API_KEY=$HERMES_OPENROUTER_KEY\"" || true)
$([ -n "$HERMES_ANTHROPIC_KEY" ] && echo "  echo \"ANTHROPIC_API_KEY=$HERMES_ANTHROPIC_KEY\"" || true)
} > "\$HOME/hermes-agent/.env"
chmod 600 "\$HOME/hermes-agent/.env"
echo "[remote] hermes-agent .env written (chmod 600)"
REMOTE_HERMES_ENV

  # Enable + start the systemd service (managed by NixOS hermes-agent.nix).
  ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "sudo systemctl enable --now hermes-agent.service" || {
    echo "::warning:: hermes-agent.service failed to start; check: journalctl -u hermes-agent -n 50" >&2
  }

  # Register the daily-report cron job inside Hermes (session-aware, persistent memory across days).
  echo "[setup-vm-nixos] registering daily-report cron in Hermes..."
  bash "$HARNESS_DIR/scripts/register-agent-daily-report.sh" "$ROOT" hermes "$SSH_TARGET" "$OCI_VM_SSH_KEY"

  # Disable the shell-cron timers so they don't fire alongside the Hermes cron.
  # The .sh scripts remain on disk for emergency manual invocation.
  echo "[setup-vm-nixos] disabling shell-cron timers (Hermes cron handles the daily report now)..."
  ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "sudo systemctl disable --now daily-progress.timer event-watch.timer || true"

  echo "[setup-vm-nixos] Hermes Agent deployed. First-run downloads Whisper Tiny (~75 MB) + NeuTTS Air (~500 MB); allow 5-10 min."
fi

# Start timers only when Hermes is NOT handling the daily report.
if [ "${HERMES_AGENT_ENABLED:-no}" = "yes" ]; then
  echo "[setup-vm-nixos] HERMES_AGENT_ENABLED=yes — skipping shell-cron timer enable (Hermes internal cron is active)."
else
  ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "sudo systemctl enable --now daily-progress.timer event-watch.timer"
fi

# Smoke test
echo "[setup-vm-nixos] running daily-progress.sh once as smoke test..."
ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "sudo systemctl start daily-progress.service" || {
  echo "::warning:: smoke test failed; check journalctl -u daily-progress on the VM" >&2
}

cat <<EOF

[setup-vm-nixos] DONE.

  VM:       $OCI_VM_NAME ($OCI_VM_REGION) — NixOS
  Public:   $OCI_VM_PUBLIC_IP
  SSH in:   ssh -i $OCI_VM_SSH_KEY $SSH_TARGET
  Bot:      ~/daily-progress-bot/ on the VM
  Timers:   daily-progress.timer + event-watch.timer
  Repo:     $REPO_OWNER/$REPO_NAME → $NOTIFICATION_SERVICE
  Cloud-portable: re-deploy to AWS Graviton / GCP Tau T2A / Hetzner ARM
                  by re-running this script with that VM's .oci-vm.env equivalent.

EOF
